In [2]:
import numpy as np
import pandas as pd

In [19]:
df_list = pd.read_csv("../data/join_list.csv", encoding = "CP949")
df_room = pd.read_csv("../data/join_room.csv", encoding = "CP949")

print(df_list.head())
print()
print(df_room.head())
print(df_list.shape[0])
print(df_room.shape[0])

    team    No member
0  TWICE  1287     미나
1  TWICE  1788     나연
2  TWICE  1408     다현
3  TWICE  1881     정연
4  TWICE  1937     지효

   floor  room name
0      3  3G-A   미나
1      3  3G-B   나연
2      3  3G-C   다현
3      4  4G-A   정연
4      4  4G-B   지효
14
9


In [16]:
df_list.join(df_room, how="left")

team    No member  floor  room name
0        TWICE  1287     미나    3.0  3G-A   미나
1        TWICE  1788     나연    3.0  3G-B   나연
2        TWICE  1408     다현    3.0  3G-C   다현
3        TWICE  1881     정연    4.0  4G-A   정연
4        TWICE  1937     지효    4.0  4G-B   지효
5        TWICE  1045     채연    4.0  4G-C   채연
6        TWICE  1525     모모    5.0  5G-A   모모
7        TWICE  1887     쯔위    5.0  5G-B   쯔위
8        TWICE  1547     사나    5.0  5G-C   사나
9   Red Velvet  1452    아이린    NaN   NaN  NaN
10  Red Velvet  1948     웬디    NaN   NaN  NaN
11  Red Velvet  1448     슬기    NaN   NaN  NaN
12  Red Velvet  1670     조이    NaN   NaN  NaN
13  Red Velvet  1565     예리    NaN   NaN  NaN

In [17]:
df_list.join(df_room, how='inner')

team    No member  floor  room name
0  TWICE  1287     미나      3  3G-A   미나
1  TWICE  1788     나연      3  3G-B   나연
2  TWICE  1408     다현      3  3G-C   다현
3  TWICE  1881     정연      4  4G-A   정연
4  TWICE  1937     지효      4  4G-B   지효
5  TWICE  1045     채연      4  4G-C   채연
6  TWICE  1525     모모      5  5G-A   모모
7  TWICE  1887     쯔위      5  5G-B   쯔위
8  TWICE  1547     사나      5  5G-C   사나

In [27]:
df_list_sampled = df_list.sort_values(by = "No", ascending = True).reset_index(drop = True)
df_list_sampled
# join 기본적으로 index 기준으로 수행

team    No member
0        TWICE  1045     채연
1        TWICE  1287     미나
2        TWICE  1408     다현
3   Red Velvet  1448     슬기
4   Red Velvet  1452    아이린
5        TWICE  1525     모모
6        TWICE  1547     사나
7   Red Velvet  1565     예리
8   Red Velvet  1670     조이
9        TWICE  1788     나연
10       TWICE  1881     정연
11       TWICE  1887     쯔위
12       TWICE  1937     지효
13  Red Velvet  1948     웬디

In [29]:
df_list.sort_values(by="No").set_index("member").join(df_room.set_index("name"), how="inner")

team    No  floor  room
채연  TWICE  1045      4  4G-C
미나  TWICE  1287      3  3G-A
다현  TWICE  1408      3  3G-C
모모  TWICE  1525      5  5G-A
사나  TWICE  1547      5  5G-C
나연  TWICE  1788      3  3G-B
정연  TWICE  1881      4  4G-A
쯔위  TWICE  1887      5  5G-B
지효  TWICE  1937      4  4G-B

In [30]:
df = pd.read_csv("../data/bike.csv")
df.head(2)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [42]:
df["season_1"] = np.where(df["season"] == 1, 1, 0)
df["season_2"] = (df["season"] == 1) + 0
df["season_3"] = (df["season"] == 1) * 1
df = df.drop("season_1", axis=1)
df = df.drop("season_2", axis=1)
df = df.drop("season_3", axis=1)
df.head(5)

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [46]:
print(pd.get_dummies(df.iloc[:,1:]).head(2))

df_dum = pd.get_dummies(df.iloc[:,1:], columns = ["season"])
df_dum.columns
df_dum.head(2)

   season  holiday  workingday  weather  temp   atemp  humidity  windspeed  \
0       1        0           0        1  9.84  14.395        81        0.0   
1       1        0           0        1  9.02  13.635        80        0.0   

   casual  registered  count  
0       3          13     16  
1       8          32     40  


holiday  workingday  weather  temp   atemp  humidity  windspeed  casual  \
0        0           0        1  9.84  14.395        81        0.0       3   
1        0           0        1  9.02  13.635        80        0.0       8   

   registered  count  season_1  season_2  season_3  season_4  
0          13     16         1         0         0         0  
1          32     40         1         0         0         0

In [49]:
pd.crosstab(df["season"], df_dum["season_2"])

season_2     0     1
season              
1         2686     0
2            0  2733
3         2733     0
4         2734     0

In [85]:
df = pd.read_csv("../data/bike.csv")

# print(df.groupby("season").mean()["count"].apply(lambda x: round(x)))
print(df.groupby("season")["count"].head())
df.groupby("season")["count"].agg(lambda x: round(x.mean()))

0        16
1        40
2        32
3        13
4         1
1323      6
1324      4
1325      7
1326      4
1327      3
2690     68
2691     31
2692     13
2693     11
2694      6
4055    130
4056     58
4057     67
4058     25
4059      8
Name: count, dtype: int64


season
1    116
2    215
3    234
4    199
Name: count, dtype: int64

In [93]:
aws = pd.read_csv("../data/AWS_sample.txt", sep = "#")

print(aws.head(2))

aws["TM"] = aws["TM"] + ":00:00"

aws.head(2)
aws.info()

   AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5886 entries, 0 to 5885
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   AWS_ID  5886 non-null   int64  
 1   TM      5886 non-null   object 
 2   TA      5886 non-null   float64
 3   Wind    5886 non-null   float64
 4   X.      5886 non-null   object 
dtypes: float64(2), int64(1), object(2)
memory usage: 230.0+ KB


In [94]:
aws = pd.read_csv("../data/AWS_sample.txt", sep = "#")
aws["TM"] = pd.to_datetime(aws["TM"])
aws.head(2)
aws.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5886 entries, 0 to 5885
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   AWS_ID  5886 non-null   int64         
 1   TM      5886 non-null   datetime64[ns]
 2   TA      5886 non-null   float64       
 3   Wind    5886 non-null   float64       
 4   X.      5886 non-null   object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 230.0+ KB


In [111]:
df = pd.read_csv("../data/bike.csv")
print(df.head(2))
print()
print(df["season"].unique())
print()
print(df["season"].value_counts())
print()
print(df.value_counts(["season"]).reset_index())
print()

print(df["season"].nunique())
print()
print(df.nunique())

              datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  

[1 2 3 4]

4    2734
3    2733
2    2733
1    2686
Name: season, dtype: int64

   season     0
0       4  2734
1       3  2733
2       2  2733
3       1  2686

4

datetime      10886
season            4
holiday           2
workingday        2
weather           4
temp             49
atemp            60
humidity         89
windspeed        28
casual          309
registered      731
count           822
dtype: int64


In [105]:
ser_time_01 = pd.Series(["2020-11-24 13", "2020-11-24 13"], name="datetime")
ser_time_01
pd.to_datetime(ser_time_01, format="%Y-%m-%d %H:%M:%S")

0   2020-11-24 13:00:00
1   2020-11-24 13:00:00
Name: datetime, dtype: datetime64[ns]

In [167]:
df = pd.read_csv("../data/diamonds.csv")

pd.crosstab(df["cut"], df["color"])

color         D     E     F     G     H     I    J
cut                                               
Fair        163   224   312   314   303   175  119
Good        662   933   909   871   702   522  307
Ideal      2834  3903  3826  4884  3115  2093  896
Premium    1603  2337  2331  2924  2360  1428  808
Very Good  1513  2400  2164  2299  1824  1204  678

In [114]:
df["cut"].value_counts(normalize=True).reset_index()

index       cut
0      Ideal  0.399537
1    Premium  0.255673
2  Very Good  0.223990
3       Good  0.090953
4       Fair  0.029848

In [119]:
print(pd.crosstab(df["cut"], df["color"], normalize = 0).sum(axis=1))
pd.crosstab(df["cut"], df["color"], normalize = 0)

cut
Fair         1.0
Good         1.0
Ideal        1.0
Premium      1.0
Very Good    1.0
dtype: float64


color             D         E         F         G         H         I  \
cut                                                                     
Fair       0.101242  0.139130  0.193789  0.195031  0.188199  0.108696   
Good       0.134937  0.190175  0.185283  0.177538  0.143090  0.106400   
Ideal      0.131502  0.181105  0.177532  0.226625  0.144541  0.097118   
Premium    0.116235  0.169458  0.169023  0.212022  0.171126  0.103546   
Very Good  0.125228  0.198643  0.179109  0.190283  0.150968  0.099652   

color             J  
cut                  
Fair       0.073913  
Good       0.062576  
Ideal      0.041576  
Premium    0.058589  
Very Good  0.056117

In [116]:
pd.crosstab(df["cut"], df["color"], normalize = 1)

color             D         E         F         G         H         I  \
cut                                                                     
Fair       0.024059  0.022864  0.032698  0.027807  0.036488  0.032276   
Good       0.097712  0.095233  0.095263  0.077134  0.084538  0.096274   
Ideal      0.418303  0.398387  0.400964  0.432519  0.375120  0.386020   
Premium    0.236605  0.238542  0.244288  0.258944  0.284200  0.263371   
Very Good  0.223321  0.244973  0.226787  0.203595  0.219653  0.222058   

color             J  
cut                  
Fair       0.042379  
Good       0.109330  
Ideal      0.319088  
Premium    0.287749  
Very Good  0.241453

In [170]:
pd.crosstab(df["cut"], df["color"], normalize = True)
# pd.crosstab(df["cut"], df["color"], normalize = True).sum()

1.0

In [135]:
df = pd.read_csv("../data/diamonds.csv")
print(df.loc[:,"price":].mean().to_frame(name="mean").transpose())
print()
print(df.loc[:, "price":].agg(["mean"]))
print()
print(df.loc[:, "price":].agg(["max", "mean"]))
print()
print(df.groupby("cut")["price"].agg(["max", "min"]))
print()
print(df.groupby(by=["cut", "color"])["price"].agg(["max", "min"]))

            price         x         y         z
mean  3932.799722  5.731157  5.734526  3.538734

            price         x         y         z
mean  3932.799722  5.731157  5.734526  3.538734

             price          x          y          z
max   18823.000000  10.740000  58.900000  31.800000
mean   3932.799722   5.731157   5.734526   3.538734

             max  min
cut                  
Fair       18574  337
Good       18788  327
Ideal      18806  326
Premium    18823  326
Very Good  18818  336

                   max  min
cut       color            
Fair      D      16386  536
          E      15584  337
          F      17995  496
          G      18574  369
          H      18565  659
          I      18242  735
          J      18531  416
Good      D      18468  361
          E      18236  327
          F      18686  357
          G      18788  394
          H      18640  368
          I      18707  351
          J      18325  335
Ideal     D      18693  367
          E      1

In [162]:
bike = pd.read_csv("../data/bike.csv")

# print(bike.groupby(by="season")["casual"].mean())
print(bike.groupby(by="season").mean()["casual"])
print()
# print(bike.groupby(by="season")["casual", "registered"].mean())
print(bike.groupby(by="season").mean().loc[:,["casual", "registered"]])
print()
# print(bike.groupby(by=["season", "holiday"])["casual"].mean())
print(bike.groupby(by=["season", "holiday"]).mean()["casual"])

season
1    15.489576
2    47.446762
3    52.220271
4    28.580834
Name: casual, dtype: float64

           casual  registered
season                       
1       15.489576  100.853686
2       47.446762  167.804610
3       52.220271  182.196853
4       28.580834  170.407462

season  holiday
1       0          15.689101
        1           8.140845
2       0          47.609683
        1          38.333333
3       0          50.773606
        1          91.958333
4       0          28.133055
        1          40.885417
Name: casual, dtype: float64

season  holiday
1       0          15.689101
        1           8.140845
2       0          47.609683
        1          38.333333
3       0          50.773606
        1          91.958333
4       0          28.133055
        1          40.885417
Name: casual, dtype: float64


In [132]:
elec = pd.read_csv("../data/elec_load.csv")
elec.head(2)

YEAR  MONTH  DAY   X1HR   X2HR   X3HR   X4HR   X5HR   X6HR   X7HR  ...  \
0  2008      1    1  39638  37682  35801  34154  33068  32529  31982  ...   
1  2008      1    2  37425  35239  33568  32171  31616  31725  32575  ...   

   X15HR  X16HR  X17HR  X18HR  X19HR  X20HR  X21HR  X22HR  X23HR  X24HR  
0  28147  28313  28683  30921  32879  33038  34031  34684  37444  38160  
1  38213  38132  38399  39796  40810  39980  40084  39630  42008  42150  

[2 rows x 27 columns]

In [134]:
elec_met = elec.melt(id_vars=["YEAR","MONTH","DAY"], var_name="Type", value_name="Type_Value")
elec_met.head()

YEAR  MONTH  DAY  Type  Type_Value
0  2008      1    1  X1HR       39638
1  2008      1    2  X1HR       37425
2  2008      1    3  X1HR       40757
3  2008      1    4  X1HR       40220
4  2008      1    5  X1HR       39056

In [136]:
pd.to_datetime([1,2,3], unit ='D', origin = pd.Timestamp('1960-01-01'))

DatetimeIndex(['1960-01-02', '1960-01-03', '1960-01-04'], dtype='datetime64[ns]', freq=None)

In [163]:
df = pd.read_csv("../data/bike.csv")
print(df.head(2))
print()
df["datetime"] = pd.to_datetime(df["datetime"])
df["wday"] = df["datetime"].dt.dayofweek
df["month"] = df["datetime"].dt.month
df["hour"] = df["datetime"].dt.hour
df.head()

              datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   datetime    10886 non-null  datetime64[ns]
 1   season      10886 non-null  int64         
 2   holiday     10886 non-null  int64         
 3   workingday  10886 non-null  int64         
 4   weather     10886 non-null  int64         
 5   temp        10886 non-null  float64       
 6   atemp       10886 non-null  float64       
 7   humidity    10886 non-null  int64         
 8   windspeed   10

In [184]:
df = pd.read_csv("../data/diamonds.csv")
print(df.head())
print()
price = df["price"]
# df["price"] = (price - min(price)) / (max(price) - min(price))
df["price"] = (price - price.min()) / (price.max() - price.min())

print()
print(df["price"].max())
print()
print(df["price"].min())
print()

   carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75


1.0

0.0



In [185]:
depth = df["depth"]
df["depth"] = (depth - depth.mean()) / depth.std()

print(df["depth"].max())
print(df["depth"].min())

12.041280468810264
-13.087481421532576
<class 'numpy.float64'>


In [192]:
def normalization(series=None):
    if series is not None:
        return (series - series.min()) / (series.max() - series.min())

def standardization(series=None):
    if series is not None:
        return (series - series.mean()) / series.std()
    
print(normalization(df["depth"]).head())
print()
print(standardization(df["depth"]).head())
print()

print(normalization(pd.Series([2,3,5,7,10])))
print()
print(standardization(pd.Series([2,3,5,7,10])))
print()

0    0.513889
1    0.466667
2    0.386111
3    0.538889
4    0.563889
Name: depth, dtype: float64
0   -0.174090
1   -1.360726
2   -3.384987
3    0.454129
4    1.082348
Name: depth, dtype: float64
0    0.000
1    0.125
2    0.375
3    0.625
4    1.000
dtype: float64
0   -1.059401
1   -0.747812
2   -0.124635
3    0.498542
4    1.433307
dtype: float64


In [10]:
import numpy as np
arr1 = np.random.normal(loc=2, scale=2, size=100)
arr2 = np.random.normal(loc=2, scale=2, size=100)

print(np.cov(arr1, arr2)[0,1])
print(np.corrcoef(arr1, arr2)[0][1])

0.20784554530385846
0.05476945528949667


In [14]:
from scipy.stats import norm
from scipy.stats import binom
from scipy.stats import poisson

print(norm.rvs(3,2, size=5))
print()
print(binom.rvs(10, 0.5, size=5))
print()
print(poisson.rvs(5, size=5))

[1.30417572 1.06832997 3.87108887 6.8903388  3.77700241]

[7 4 3 7 5]

[ 4  5 12  2  4]


In [17]:
np.array([[[1],[2],[3]]]).ndim

3