In [1]:
1 + 1

2

In [2]:
1 + 1
2 + 2

4

# Title 1
### Title 3
<br/>
$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$

In [3]:
0b10

2

In [4]:
arr=[1,2,3]
truple=(1,2,3)
print("%s %s %s" % (arr[0], arr[1], arr[2]))
print("%s, %s, %s" % truple)

name = "rolroralra"
age = 20
print("Hello, {}. I am {}.".format(name, age))
print("Hello, {1}. You are {0}.".format(age, name))

person = {'name': 'Eric', 'age': 74}
print("Hello, {name}. You are {age}.".format(name=person['name'], age=person['age']))
print("Hello, {name}. You are {age}.".format(**person))


print(f"Hello, {name}. You are {age}.")

1 2 3
1, 2, 3
Hello, rolroralra. I am 20.
Hello, rolroralra. You are 20.
Hello, Eric. You are 74.
Hello, Eric. You are 74.
Hello, rolroralra. You are 20.


In [5]:
print('abc')
print("abc")
print('''abcd
efg
''')

print("""abcd
efg
""")

abc
abc
abcd
efg

abcd
efg



In [6]:
tx="hello!"
print(tx[0])
print(tx[-1])
print(tx[2:])
print(tx[:2])
print(tx[-1::-1])
print(tx[-1::-1])

print(~2)

arr=[1,2,3]
print(arr * 2)
print(2 in arr)

import numpy as np
cc = np.array([1,2,3])
dd = np.array([4,5,6])
cc + dd
arr.append([6,6])
print(arr)
arr.extend([7,7])
print(arr)

h
!
llo!
he
!olleh
!olleh
-3
[1, 2, 3, 1, 2, 3]
True
[1, 2, 3, [6, 6]]
[1, 2, 3, [6, 6], 7, 7]


In [7]:
aa = (1, 2, [5,6,7])
print(aa[2][2])
print(aa)
print(type(aa))

import keyword
print(keyword.kwlist)

7
(1, 2, [5, 6, 7])
<class 'tuple'>
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [8]:
level = ["A", "B", "C", "D", "F"]
mine = "C"
if mine in level[:1]:
    print("Pass")
elif mine == level[2]:
    print("Retake")
else:
    print("Fail")

print(int(1.1))
print(float(1.1))
print(complex(1,2))

Retake
1
1.1
(1+2j)


In [9]:
for n in range(10):
    print(n)
    
listt = ["a", "b", "c"]
for i in listt:
    print(i)

a = [(1,2), (3,4), (5,6)]
for (first, second) in a:
    print(first, second)
    
for v in a:
    print(v)
    
a = [2, 6, 7, 8, 9]
[a[l] for l in range(len(a)) if l % 2 == 0 and a[l] % 2 == 0]

0
1
2
3
4
5
6
7
8
9
a
b
c
1 2
3 4
5 6
(1, 2)
(3, 4)
(5, 6)


[2]

In [10]:
a = [2, 6, 7, 8, 9]
list_even = list()
for num in a:
    if num % 2 ==0:
#         list_even.append(num)
#       list_even += [num]
        list_even.extend([num])
print(list_even)


print([num for num in a if num % 2 == 0])


b = [6,2,1,4,3,5,7]
print(sorted(b))
print(b)
b.sort()
print(b)
b.sort(reverse=True)
print(b)


[2, 6, 8]
[2, 6, 8]
[1, 2, 3, 4, 5, 6, 7]
[6, 2, 1, 4, 3, 5, 7]
[1, 2, 3, 4, 5, 6, 7]
[7, 6, 5, 4, 3, 2, 1]


In [11]:
def udf_02(aa = 2):
    print(aa)
    
udf_02()
udf_02(100)

def udf_03(aa, bb):
    return aa + bb

print(udf_03(10, 20))

2
100
30


In [12]:
set1 = {1,2,3}
set2 = {3,4,5}
print(set1 & set2)
#print(set1.intersection(set2))
print(set1 | set2)
#print(set1.union(set2))
print(set1 - set2)
#print(set1.difference(set2))
print(set1 ^ set2)
#print(set1.symmetric_difference(set2))

{3}
{1, 2, 3, 4, 5}
{1, 2}
{1, 2, 4, 5}


In [13]:
import numpy as np

arr = np.array([1,2,3])
print(arr)
print(arr.shape)

arr2 = np.zeros((2,3))
print(arr2.shape)



[1 2 3]
(3,)
(2, 3)


In [14]:
import numpy as np

# ndarray shallow copy
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

arr_sub = arr[0, 0:2]
print(arr_sub)

arr[0,0:2] = [99, 98]
print(arr)
print(arr_sub)
print()

# ndarray deep copy
arr = np.array([[1,2,3], [4,5,6]])
print(arr)

arr_sub = arr[0, 0:2].copy()
print(arr_sub)

arr[0,0:2] = [99, 98]
print(arr)
print(arr_sub)
print()

# python stadard list
array = [[1,2,3],[4,5,6]]
temp = array[0][0:2]
print(temp)
array[0][0:2] = [99, 98]
print(array)
print(temp)

[[1 2 3]
 [4 5 6]]
[1 2]
[[99 98  3]
 [ 4  5  6]]
[99 98]

[[1 2 3]
 [4 5 6]]
[1 2]
[[99 98  3]
 [ 4  5  6]]
[1 2]

[1, 2]
[[99, 98, 3], [4, 5, 6]]
[1, 2]


In [15]:
import numpy as np
nums = [1,2,2,5,8,8]
print(len(nums))
print(set(nums))
print(list(set(nums)))
print(np.unique(nums))

6
{8, 1, 2, 5}
[8, 1, 2, 5]
[1 2 5 8]


In [16]:
aa = [1,2,3,4,5]

def list_mean(list=[]):
    if len(list) == 0:
        return 0
    
    return sum(list) / len(list)

print(list_mean(aa))

import functools 
print(functools.reduce(lambda x, y: x + y, aa) / len(aa))


3.0
3.0


In [17]:
import numpy as np
import time

curr_time = time.time()
print(f"time: {curr_time}")
np.random.seed(int(curr_time))

normal_sample = np.random.normal(loc = 2, scale = 2, size = 100)
print(normal_sample)
print(f"mean: {normal_sample.mean()}")
print(f"std : {normal_sample.std()}")

time: 1606116090.8788269
[ 1.41894428  4.01985532  2.97462568  1.04063467 -0.51857174 -0.25740004
  1.6506243  -0.3252404   1.74497877 -3.22825261 -0.26236229 -1.91479447
 -2.45534308  1.91192959  3.32348702 -0.05790362  1.39969158  0.22599503
  2.55284782  5.9772229   3.31569111  0.60050652  3.27231328  1.33125052
  1.26977096  4.32455275  3.94640671  0.25418675  3.43239122  2.139042
 -0.39202605 -0.20784562 -1.59126579  3.6422841   2.77226009  3.40323812
  5.35566844  2.57088606  2.58223012  2.78182121  4.04484022  1.10744403
 -0.90433554  0.21039339  2.57318674  1.11976232  0.85727943  2.56167626
  2.80318335  0.74903216  3.76936703  2.83045768  3.75229087 -0.80996576
  0.86039944  2.34649035  0.90427278 -1.5057142   0.33993159  1.17672367
  3.9060299   0.93165243  1.41692111  3.73294585  1.17473705  1.56336429
  5.56616449  0.93890306 -1.2287818   2.22285312  1.24503183  1.89060215
  1.10287076  2.23529761  2.46812824  2.17441156  3.08108767  0.22457326
  3.08135733  2.54031441  1.

In [18]:
import pandas as pd
data = pd.DataFrame([[1,'a'],[2,'b'],[3,'c'],[4,'d']])
print(type(data))
print(type(data.index))
print(type(data.values))
print(data)
print()

ser2 = pd.Series([2,4,6,8], index=["a","b","c","d"])
print(ser2)

ser = pd.Series([2,4,8,9,15])
print(ser.astype("str") + "a")

print((ser[ser == ser.min()].index[0]))
print(ser)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.indexes.range.RangeIndex'>
<class 'numpy.ndarray'>
   0  1
0  1  a
1  2  b
2  3  c
3  4  d

a    2
b    4
c    6
d    8
dtype: int64
0     2a
1     4a
2     8a
3     9a
4    15a
dtype: object
0
0     2
1     4
2     8
3     9
4    15
dtype: int64


In [19]:
df = pd.DataFrame({
    "aa": [1,2,3],
    "bb": ["a","b","c"]
})
print(df)

   aa bb
0   1  a
1   2  b
2   3  c


In [20]:
import numpy as np
import pandas as pd

df = pd.DataFrame(np.arange(6).reshape(3,2), index=["a","b","c"], columns=["aa","bb"])
print(df)
print(df.aa)
print(df["aa"])
print(df["aa"][1])
print(df.iloc[0,:])
print(df.loc["a", "aa"])

   aa  bb
a   0   1
b   2   3
c   4   5
a    0
b    2
c    4
Name: aa, dtype: int32
a    0
b    2
c    4
Name: aa, dtype: int32
2
aa    0
bb    1
Name: a, dtype: int32
0


In [21]:
print(df.columns)
df.columns = ['xx', 'yy']
df.columns.values[0] = 'XX'
print(df)

df.rename(columns={"XX":"obs"})

print(df.shape)

Index(['aa', 'bb'], dtype='object')
   XX  yy
a   0   1
b   2   3
c   4   5
(3, 2)


In [22]:
df = pd.read_csv("data/bike.csv")
df.head(2)
# df.iloc[:2]

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40

In [23]:
aws = pd.read_csv("data/AWS_sample.txt", sep="#")
aws.head(2)
# aws.iloc[:2]

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =

In [24]:
df = pd.read_excel("data/iris_xlsx.xlsx")
df.head(2)
# df.iloc[:2]

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [31]:
# df_sub = df[df.season == 1]
print(df.head())
df_sub = df.loc[df["season"] == 1, :]  # 권장
print(df_sub)

# print(df_sub.head(2))
# print(df_sub.shape)
# print()

# # df_sub2 = df[(df.season == 1) & (df.holiday == 1)]
# df_sub2 = df.loc[(df["season"] == 1) & (df["holiday"] == 1), :]
# print(df_sub2.head(2))
# print(df_sub2.shape)

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa


KeyError: 'season'

In [32]:
import pandas as pd
df = pd.read_csv("data/bike.csv")
df_sub = df.loc[df["casual"] >= df["casual"].quantile(0.99), :]
print(df_sub["casual"].quantile([0,1]))
print(df_sub["casual"].min())
print(df_sub["casual"].max())
print(len(df_sub))

0.0    241.0
1.0    367.0
Name: casual, dtype: float64
241
367
109


In [33]:
df = pd.read_csv("data/iris_missing.csv")
df_sub = df.head()
print(df_sub)
print(f"length: {len(df_sub)}")
print()

print(df_sub.fillna(0))
print()

print(df_sub[df_sub.columns[1]].fillna(99))
print()

print(np.mean(df.iloc[:,0]))
print(np.nanmean(df.iloc[:,0]))
print(df.iloc[:,0].sum() / (len(df) - df.iloc[:,0].isna().sum()))

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          NaN           NaN          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
length: 5

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          0.0           0.0          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

0    99.0
1     3.0
2     3.2
3     3.1
4     3.6
Name: Sepal.Width, dtype: float64

5.853846153846154
5.8538461538461535
5.8538461538461535


In [35]:
print(df_sub.fillna(value = {df_sub.columns[0]: 80, df_sub.columns[1]: -77}))

# df_sub["test"] = df_sub[df_sub.columns[1]].fillna(df_sub[df_sub.columns[1]].mean())
df_sub.loc["test",:] = df_sub[df_sub.columns[1]].fillna(df_sub[df_sub.columns[1]].mean())
# df_sub["test2"] = df_sub[df_sub.columns[1]].fillna(df_sub[df_sub.columns[1]].mean())
print(df_sub)

      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  test2
0              5.1        -77.0           NaN          0.2  setosa  3.225
1              4.9          3.0           1.4          0.2  setosa  3.000
2              4.7          3.2           1.3          0.2  setosa  3.200
3              4.6          3.1           1.5          0.2  setosa  3.100
4              5.0          3.6           1.4          0.2  setosa  3.600
test          80.0        -77.0           NaN          NaN     NaN  3.225
      Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species  test2
0              5.1          NaN           NaN          0.2  setosa  3.225
1              4.9          3.0           1.4          0.2  setosa  3.000
2              4.7          3.2           1.3          0.2  setosa  3.200
3              4.6          3.1           1.5          0.2  setosa  3.100
4              5.0          3.6           1.4          0.2  setosa  3.600
test           NaN          NaN       

In [45]:
import numpy as np
import pandas as pd
df = pd.read_csv("data/iris_missing.csv")
df_mis = df.iloc[5:9,0:-1]
print(df_mis.head())
print()

print(df_mis.iloc[:,0].replace(5.0, np.nan))
print(df_mis.replace(1.4, np.nan))

print(df_mis.dropna(how='all'))

   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
6           NaN          NaN           NaN          NaN
7           5.0          3.4           NaN          0.2
8           4.4          2.9           1.4          0.2

5    5.4
6    NaN
7    NaN
8    4.4
Name: Sepal.Length, dtype: float64
   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
6           NaN          NaN           NaN          NaN
7           5.0          3.4           NaN          0.2
8           4.4          2.9           NaN          0.2
   Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
5           5.4          3.9           1.7          0.4
7           5.0          3.4           NaN          0.2
8           4.4          2.9           1.4          0.2


In [46]:
print(df_mis.iloc[:,0].isnull())
print()
print(df_mis.iloc[:,0].isna())

5    False
6     True
7    False
8    False
Name: Sepal.Length, dtype: bool
5    False
6     True
7    False
8    False
Name: Sepal.Length, dtype: bool


In [48]:
print(df_mis.iloc[:,0].notnull())
print()
print(df_mis.iloc[:,0].notna())

5     True
6    False
7     True
8     True
Name: Sepal.Length, dtype: bool

5     True
6    False
7     True
8     True
Name: Sepal.Length, dtype: bool


In [50]:
print(df_mis.isna().sum())

Sepal.Length    1
Sepal.Width     1
Petal.Length    2
Petal.Width     1
dtype: int64


In [53]:
df = pd.DataFrame([["A",3], ["C",1], ["B", 2]], columns=["class","value"])
print(df.sort_values(by=df.columns[0], ascending=False))

  class  value
1     C      1
2     B      2
0     A      3


In [66]:
df = pd.read_csv("data/bike.csv")
df_sub = df.iloc[:6, 9:12]
print(df_sub)
print()

df_sub = df_sub.sort_values(by=list(df_sub.columns[0:2].values), ascending = [False, True])
print(df_sub)
print()

df_sub = df_sub.reset_index(drop = True)
print(df_sub)
print()

   casual  registered  count
0       3          13     16
1       8          32     40
2       5          27     32
3       3          10     13
4       0           1      1
5       0           1      1

   casual  registered  count
1       8          32     40
2       5          27     32
3       3          10     13
0       3          13     16
4       0           1      1
5       0           1      1

   index  casual  registered  count
0      1       8          32     40
1      2       5          27     32
2      3       3          10     13
3      0       3          13     16
4      4       0           1      1
5      5       0           1      1



In [70]:
import time
bike = pd.read_csv("data/bike.csv")
np.random.seed(int(time.time()))

print(f"length: {len(bike)}")
print(len(bike) * 0.2)
print()

bike_sample01 = bike.sample(n = 10, replace = False)
bike_sample02 = bike.sample(frac = 0.2, replace = False)
print(bike_sample01)
print()

print(bike_sample02)
print()

length: 10886
2177.2000000000003

                  datetime  season  holiday  workingday  weather   temp  \
8146   2012-06-19 19:00:00       2        0           1        1  32.80   
8440   2012-07-13 01:00:00       3        0           1        2  27.88   
5196   2011-12-10 14:00:00       4        0           0        1  13.94   
1129   2011-03-11 17:00:00       1        0           1        1  13.94   
10364  2012-11-17 06:00:00       4        0           0        1   9.84   
8672   2012-08-03 17:00:00       3        0           1        2  34.44   
9224   2012-09-07 17:00:00       3        0           1        1  31.98   
5867   2012-01-19 16:00:00       1        0           1        1  10.66   
2589   2011-06-15 19:00:00       2        0           1        1  28.70   
8845   2012-08-10 22:00:00       3        0           1        1  29.52   

        atemp  humidity  windspeed  casual  registered  count  
8146   38.635        59    15.0013      82         432    514  
8440   31.82

In [76]:
bike_sample = bike.sample(n = 3)
bike_sample = bike_sample.reset_index()
print(bike_sample)
print()

bike_sample.reindex(list(range(4)))
print(bike_sample)
print()

print(bike.columns)
print()

bike2 = bike.loc[:, ["season","holiday","temp"]]
bike2 = bike2.set_index(["season","holiday"])
print(bike2)

   index             datetime  season  holiday  workingday  weather   temp  \
0   9349  2012-09-12 22:00:00       3        0           1        1  22.96   
1   4102  2011-10-02 23:00:00       4        0           0        1  14.76   
2   3211  2011-08-03 17:00:00       3        0           1        2  28.70   

    atemp  humidity  windspeed  casual  registered  count  
0  26.515        64     6.0032      23         189    212  
1  18.180        81     6.0032       6          19     25  
2  33.335        79     0.0000      47         378    425  

   index             datetime  season  holiday  workingday  weather   temp  \
0   9349  2012-09-12 22:00:00       3        0           1        1  22.96   
1   4102  2011-10-02 23:00:00       4        0           0        1  14.76   
2   3211  2011-08-03 17:00:00       3        0           1        2  28.70   

    atemp  humidity  windspeed  casual  registered  count  
0  26.515        64     6.0032      23         189    212  
1  18.180    

In [80]:
bike_temp = bike.loc[:,"season"].astype("str") + "월"
print(bike_temp)

0        1월
1        1월
2        1월
3        1월
4        1월
         ..
10881    4월
10882    4월
10883    4월
10884    4월
10885    4월
Name: season, Length: 10886, dtype: object


In [87]:
df = pd.read_csv("data/bike.csv")
df_1 = df.head()
df_2 = df.tail()

print(df_1)
print()
print(df_2)
print()
print(len(df_1), len(df_2))
print()

df_bind = pd.concat([df_1, df_2])
print(df_bind.shape)
print(df_bind)
print()

print(pd.concat([df_1, df_2.reset_index(drop=True)], axis='columns'))

              datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1  

                  datetime  season  holiday  workingday  weather   temp  \
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14

dict