# 데이터 입출력
## 데이터 입력
- `pd.read_csv('filepath', sep=',')`
- `pd.read_excel('filepath', sheet_name='Sheet1')`
- `pd.read_json('filepath')`

## 데이터 출력
- `df.to_csv('filepath', sep=',', index=False)`
- `df.to_excel('filepath', sheet_name='Output')`
- `df.to_json('filepath', indent=2)`

```python
df.to_json(
    path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None,
    orient: "Literal['split', 'records', 'index', 'table', 'columns', 'values'] | None" = None,
    date_format: 'str | None' = None,
    double_precision: 'int' = 10,
    force_ascii: 'bool_t' = True,
    date_unit: 'TimeUnit' = 'ms',
    default_handler: 'Callable[[Any], JSONSerializable] | None' = None,
    lines: 'bool_t' = False,
    compression: 'CompressionOptions' = 'infer',
    index: 'bool_t | None' = None,
    indent: 'int | None' = None,
    storage_options: 'StorageOptions | None' = None,
    mode: "Literal['a', 'w']" = 'w',
) -> 'str | None'
```

In [5]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('../data/bike.csv')
df.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3  2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4  2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [6]:
df = pd.read_csv('../data/AWS_sample.txt', sep='#')
df.head()

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =
2     108  2016-07-01 02  23.7   3.8  =
3     108  2016-07-01 03  23.3   3.0  =
4     108  2016-07-01 04  23.5   2.1  =

In [13]:
#!pip install openpyxl
excelFile = pd.ExcelFile('../data/iris_xlsx.xlsx')

print(excelFile.sheet_names)
df = pd.read_excel('../data/iris_xlsx.xlsx', sheet_name=excelFile.sheet_names[0])
df.head()

['Sheet1']


Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

# 필터링

In [15]:
df = pd.read_json('../data/bike.json')
df.head()

datetime  season  holiday  workingday  weather  temp   atemp  \
0 2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1 2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2 2011-01-01 02:00:00       1        0           0        1  9.02  13.635   
3 2011-01-01 03:00:00       1        0           0        1  9.84  14.395   
4 2011-01-01 04:00:00       1        0           0        1  9.84  14.395   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32  
3        75        0.0       3          10     13  
4        75        0.0       0           1      1

In [18]:
df_sub = df[df['season'] == 1]

df_sub.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
Index: 2686 entries, 0 to 6784
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   datetime    2686 non-null   datetime64[ns]
 1   season      2686 non-null   int64         
 2   holiday     2686 non-null   int64         
 3   workingday  2686 non-null   int64         
 4   weather     2686 non-null   int64         
 5   temp        2686 non-null   float64       
 6   atemp       2686 non-null   float64       
 7   humidity    2686 non-null   int64         
 8   windspeed   2686 non-null   float64       
 9   casual      2686 non-null   int64         
 10  registered  2686 non-null   int64         
 11  count       2686 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(8)
memory usage: 272.8 KB


(10886, 12)

In [17]:
print(np.unique(df.season))

set(df.season)

[1 2 3 4]


{1, 2, 3, 4}

In [28]:
df[(df.season == 1) | (df.season == 2)]

0         True
1         True
2         True
3         True
4         True
         ...  
10881    False
10882    False
10883    False
10884    False
10885    False
Name: season, Length: 10886, dtype: bool

# np.isin(array_like1, array_like2)
- `np.isin(arr1, arr2)`
- `np.in1d(arr1, arr2)`
  
```python
np.isin(
    element,
    test_elements,
    assume_unique=False,
    invert=False,
    *,
    kind=None,
)
```

In [30]:
df[np.isin(df.season, [1, 2])].shape

assert (df[np.isin(df.season, [1, 2])].index == df[(df.season == 1) | (df.season == 2)].index).all()
assert (df[np.isin(df.season, [1, 2])].index == df.iloc[np.isin(df.season, [1, 2])].index).all()
assert (df[np.isin(df.season, [1, 2])].index == df.loc[np.isin(df.season, [1, 2])].index).all()

assert (df[df.season.isin([1, 2])].index == df[np.isin(df.season, [1, 2])].index).all()

# df[np.isin(df.season, [1, 2])]
# np.isin(df.season, [1, 2])

df[df.season.isin([1,2])]

datetime  season  holiday  workingday  weather   temp   atemp  \
0    2011-01-01 00:00:00       1        0           0        1   9.84  14.395   
1    2011-01-01 01:00:00       1        0           0        1   9.02  13.635   
2    2011-01-01 02:00:00       1        0           0        1   9.02  13.635   
3    2011-01-01 03:00:00       1        0           0        1   9.84  14.395   
4    2011-01-01 04:00:00       1        0           0        1   9.84  14.395   
...                  ...     ...      ...         ...      ...    ...     ...   
8146 2012-06-19 19:00:00       2        0           1        1  32.80  38.635   
8147 2012-06-19 20:00:00       2        0           1        1  32.80  37.880   
8148 2012-06-19 21:00:00       2        0           1        1  31.16  35.605   
8149 2012-06-19 22:00:00       2        0           1        1  29.52  34.850   
8150 2012-06-19 23:00:00       2        0           1        1  29.52  34.850   

      humidity  windspeed  casual  registered  count  
0           81     0.0000       3          13     16  
1           80     0.0000       8          32     40  
2           80     0.0000       5          27     32  
3           75     0.0000       3          10     13  
4           75     0.0000       0           1      1  
...        ...        ...     ...         ...    ...  
8146        59    15.0013      82         432    514  
8147        55    16.9979      59         399    458  
8148        62    11.0014      37         239    276  
8149        79     6.0032      51         240    291  
8150        79     8.9981      23         102    125  

[5419 rows x 12 columns]

# 참고사항: 행렬곱, ndarray 곱

In [52]:
mat = np.matrix([[1, 2], [3, 4]])
print(f"mat = \n{mat}\n")
print(f"mat + 3 = \n{mat + 3}\n")
print(f"mat + mat = \n{mat + mat}\n")
print(f"mat * 3 = \n{mat * 3}\n")
print(f"mat ** 2 = \n{mat ** 2}\n")
print(f"mat * mat = \n{mat * mat}\n")
print(f"mat.dot(mat) = \n{mat.dot(mat)}\n")

assert (mat * mat == mat ** 2).all()
assert (mat * mat == mat.dot(mat)).all()
assert (mat * 2 == mat + mat).all()


mat = 
[[1 2]
 [3 4]]

mat + 3 = 
[[4 5]
 [6 7]]

mat + mat = 
[[2 4]
 [6 8]]

mat * 3 = 
[[ 3  6]
 [ 9 12]]

mat ** 2 = 
[[ 7 10]
 [15 22]]

mat * mat = 
[[ 7 10]
 [15 22]]

mat.dot(mat) = 
[[ 7 10]
 [15 22]]



In [58]:
ndarr = np.array([[1, 2], [3, 4]])
print(f"ndarr = \n{ndarr}\n")
print(f"ndarr + 3 = \n{ndarr + 3}\n")
print(f"ndarr + ndarr = \n{ndarr + ndarr}\n")
print(f"ndarr * 3 = \n{ndarr * 3}\n")
print(f"ndarr ** 2 = \n{ndarr ** 2}\n")
print(f"ndarr * ndarr = \n{ndarr * ndarr}\n")
print(f"ndarr.dot(ndarr) = \n{ndarr.dot(ndarr)}\n")

assert (ndarr * ndarr != ndarr.dot(ndarr)).any()
assert (ndarr * ndarr == ndarr ** 2).all()
assert (ndarr * 2 == ndarr + ndarr).all()

ndarr = 
[[1 2]
 [3 4]]

ndarr + 3 = 
[[4 5]
 [6 7]]

ndarr + ndarr = 
[[2 4]
 [6 8]]

ndarr * 3 = 
[[ 3  6]
 [ 9 12]]

ndarr ** 2 = 
[[ 1  4]
 [ 9 16]]

ndarr * ndarr = 
[[ 1  4]
 [ 9 16]]

ndarr.dot(ndarr) = 
[[ 7 10]
 [15 22]]



# Outlier 처리 (이상치 처리)
- `df.quantile([.01, .99], numeric_only=True)`

```python
df.quantile(
    q: 'float | AnyArrayLike | Sequence[float]' = 0.5,
    axis: 'Axis' = 0,
    numeric_only: 'bool' = False,
    interpolation: 'QuantileInterpolation' = 'linear',
    method: "Literal['single', 'table']" = 'single',
) -> 'Series | DataFrame'
```

In [69]:
df = pd.read_csv('../data/bike.csv')

df.head()

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10886 entries, 0 to 10885
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   datetime    10886 non-null  object 
 1   season      10886 non-null  int64  
 2   holiday     10886 non-null  int64  
 3   workingday  10886 non-null  int64  
 4   weather     10886 non-null  int64  
 5   temp        10886 non-null  float64
 6   atemp       10886 non-null  float64
 7   humidity    10886 non-null  int64  
 8   windspeed   10886 non-null  float64
 9   casual      10886 non-null  int64  
 10  registered  10886 non-null  int64  
 11  count       10886 non-null  int64  
dtypes: float64(3), int64(8), object(1)
memory usage: 1020.7+ KB


In [25]:
df.quantile(.99, numeric_only=True).season

season          4.0000
holiday         1.0000
workingday      1.0000
weather         3.0000
temp           36.0800
atemp          40.1500
humidity      100.0000
windspeed      35.0008
casual        240.1500
registered    697.0000
count         774.1500
Name: 0.99, dtype: float64

In [26]:
df.quantile([.0, .25, .50, .75, 1.0], numeric_only=True)

season  holiday  workingday  weather   temp   atemp  humidity  \
0.00     1.0      0.0         0.0      1.0   0.82   0.760       0.0   
0.25     2.0      0.0         0.0      1.0  13.94  16.665      47.0   
0.50     3.0      0.0         1.0      1.0  20.50  24.240      62.0   
0.75     4.0      0.0         1.0      2.0  26.24  31.060      77.0   
1.00     4.0      1.0         1.0      4.0  41.00  45.455     100.0   

      windspeed  casual  registered  count  
0.00     0.0000     0.0         0.0    1.0  
0.25     7.0015     4.0        36.0   42.0  
0.50    12.9980    17.0       118.0  145.0  
0.75    16.9979    49.0       222.0  284.0  
1.00    56.9969   367.0       886.0  977.0

In [77]:
percentile_1, percentile_99 = tuple(df['casual'].quantile([0.01, 0.99]).values)

cond_1 = df['casual'] >= percentile_1
cond_2 = df['casual'] <= percentile_99

df[cond_1 & cond_2]

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
...                    ...     ...      ...         ...      ...    ...   
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14.76   
10883  2012-12-19 21:00:00       4        0           1        1  13.94   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10777 rows x 12 columns]

# 결측치 처리

## 결측치 파악
- `df.isna().sum()`
- `df.isnull()` == `df.isna()`
- `df.notnull()` == `df.notna()`

### 결측치가 하나라도 존재하는 행 개수
- `df.isna().any(axis=1).sum()`

### 결측치가 하나라도 존재하는 인덱스 목록
- `df[df.isna().any(axis=1)].index.tolist()`

## 결측치 치환
- `df['column'].fillna(value)`
- `df['column'].fillna(method='ffill', limit=10)`
- `df['column'].fillna(method='bfill')`
- `df['column'].replace(oldValue, newValue)`

```python
df.fillna(
    value: 'Hashable | Mapping | Series | DataFrame | None' = None,
    *,
    method: 'FillnaOptions | None' = None,
    axis: 'Axis | None' = None,
    inplace: 'bool_t' = False,
    limit: 'int | None' = None,
    downcast: 'dict | None | lib.NoDefault' = <no_default>,
) -> 'Self | None'
```

## 결측치 제거
- `df.dropna()`
- `df.dropna(how='any', axis=0)`
- `df.dropna(how='all')`

```python
df.dropna(
    *,
    axis: 'Axis' = 0,
    how: 'AnyAll | lib.NoDefault' = <no_default>,
    thresh: 'int | lib.NoDefault' = <no_default>,
    subset: 'IndexLabel | None' = None,
    inplace: 'bool' = False,
    ignore_index: 'bool' = False,
) -> 'DataFrame | None'
```

### 추가 함수 (df.isin)
- `df.isin(['A', 'B'])`
- `df['column'].isin([1, 2, 3])`

```python
df.isin(values: 'Series | DataFrame | Sequence | Mapping') -> 'DataFrame'
```

## 정렬과 reset_index
- `df_new.sort_values(by = ['Petal.Length', 'Petal.Width']).reset_index(drop=True)`

### df.sort_values, df.sort_index
- `df.sort_values('column')`
- `df.sort_values(['column1', 'column2'], ascending=False)`

```python
df.sort_values(
    by: 'IndexLabel',
    *,
    axis: 'Axis' = 0,
    ascending: 'bool | list[bool] | tuple[bool, ...]' = True,
    inplace: 'bool' = False,
    kind: 'SortKind' = 'quicksort',
    na_position: 'str' = 'last',
    ignore_index: 'bool' = False,
    key: 'ValueKeyFunc | None' = None,
) -> 'DataFrame | None'
```

### df.reset_index
- `df.reset_index(drop=True)`
```python
df.reset_index(
    level: 'IndexLabel | None' = None,
    *,
    drop: 'bool' = False,
    inplace: 'bool' = False,
    col_level: 'Hashable' = 0,
    col_fill: 'Hashable' = '',
    allow_duplicates: 'bool | lib.NoDefault' = <no_default>,
    names: 'Hashable | Sequence[Hashable] | None' = None,
) -> 'DataFrame | None'
```

## 임의 추출
- `df.sample(n = 10).reset_index(drop=False)`
- `df.sample(frac=0.1, replace=True).reset_index()`

```python
df.sample(
    n: 'int | None' = None,
    frac: 'float | None' = None,
    replace: 'bool_t' = False,
    weights=None,
    random_state: 'RandomState | None' = None,
    axis: 'Axis | None' = None,
    ignore_index: 'bool_t' = False,
) -> 'Self'
```

## 색인 (reset_index, set_index)
- `df.sample(n = 10).reset_index(drop=False)`
- `df.sample(frac=0.1, replace=True).reset_index()`
- `df[['column1', 'column2', 'column3']].set_index(['column1', 'column2'])`
- `df.xs(key='index1_value')`
- `df.xs(key=('index1_value', 'index2_value')`

```python
df.reset_index(
    level: 'IndexLabel | None' = None,
    *,
    drop: 'bool' = False,
    inplace: 'bool' = False,
    col_level: 'Hashable' = 0,
    col_fill: 'Hashable' = '',
    allow_duplicates: 'bool | lib.NoDefault' = <no_default>,
    names: 'Hashable | Sequence[Hashable] | None' = None,
) -> 'DataFrame | None'
```

```python
df.set_index(
    keys,
    *,
    drop: 'bool' = True,
    append: 'bool' = False,
    inplace: 'bool' = False,
    verify_integrity: 'bool' = False,
) -> 'DataFrame | None'
```

```python
df2.xs(
    key: 'IndexLabel',
    axis: 'Axis' = 0,
    level: 'IndexLabel | None' = None,
    drop_level: 'bool_t' = True,
) -> 'Self'
```

## 속성 변환 (df.astype)
- `df['season'].astype('str')`
- `df['holiday'].astype('bool')`

```python
df.astype(
    dtype,
    copy: 'bool_t | None' = None,
    errors: 'IgnoreRaise' = 'raise',
) -> 'Self'
```

## 데이터 합치기

In [32]:
df = pd.read_csv('../data/bike.csv')

df.head()

df['season'].astype('str')
df['holiday'].astype('bool').unique()

array([False,  True])

In [34]:
# df

df['Sepal.Length'].mean()

datetime  season  holiday  workingday  weather   temp  \
0      2011-01-01 00:00:00       1        0           0        1   9.84   
1      2011-01-01 01:00:00       1        0           0        1   9.02   
2      2011-01-01 02:00:00       1        0           0        1   9.02   
3      2011-01-01 03:00:00       1        0           0        1   9.84   
4      2011-01-01 04:00:00       1        0           0        1   9.84   
...                    ...     ...      ...         ...      ...    ...   
10881  2012-12-19 19:00:00       4        0           1        1  15.58   
10882  2012-12-19 20:00:00       4        0           1        1  14.76   
10883  2012-12-19 21:00:00       4        0           1        1  13.94   
10884  2012-12-19 22:00:00       4        0           1        1  13.94   
10885  2012-12-19 23:00:00       4        0           1        1  13.12   

        atemp  humidity  windspeed  casual  registered  count  
0      14.395        81     0.0000       3          13     16  
1      13.635        80     0.0000       8          32     40  
2      13.635        80     0.0000       5          27     32  
3      14.395        75     0.0000       3          10     13  
4      14.395        75     0.0000       0           1      1  
...       ...       ...        ...     ...         ...    ...  
10881  19.695        50    26.0027       7         329    336  
10882  17.425        57    15.0013      10         231    241  
10883  15.910        61    15.0013       4         164    168  
10884  17.425        61     6.0032      12         117    129  
10885  16.665        66     8.9981       4          84     88  

[10886 rows x 12 columns]

In [84]:
np.nanmean(df['Sepal.Length'])

5.8538461538461535

In [85]:
df['Sepal.Length'].isna().sum()

7

In [86]:
df.isna().sum()

Sepal.Length     7
Sepal.Width     13
Petal.Length    14
Petal.Width      6
Species          0
dtype: int64

In [104]:
# 결측치 레코드 개수 구하기
df.isna().any(axis=1).sum()

24

In [31]:
# 결측치가 하나라도 존재하는 레코드의 인덱스 목록 가져오기
na_indexes = df[df.isna().any(axis=1)].index.tolist()
na_indexes[:5]

[]

In [123]:
df['Sepal.Length'].isin([6.5])

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147     True
148    False
149    False
Name: Sepal.Length, Length: 150, dtype: bool

In [43]:
df = pd.read_csv('../data/iris_missing.csv')

df[df.isna().any(axis=1)].info()

<class 'pandas.core.frame.DataFrame'>
Index: 24 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  17 non-null     float64
 1   Sepal.Width   11 non-null     float64
 2   Petal.Length  10 non-null     float64
 3   Petal.Width   18 non-null     float64
 4   Species       24 non-null     object 
dtypes: float64(4), object(1)
memory usage: 1.1+ KB


In [42]:
df.dropna()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
..            ...          ...           ...          ...        ...
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica

[126 rows x 5 columns]

In [121]:
df['Petal.Length'].isin([1,2])

df.fillna

0      False
1      False
2      False
3      False
4      False
       ...  
145    False
146    False
147    False
148    False
149    False
Name: Petal.Length, Length: 150, dtype: bool

In [124]:
df

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             5.1          NaN           NaN          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           NaN          2.5           NaN          NaN  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          NaN  virginica

[150 rows x 5 columns]

In [50]:
df_new = df.dropna()

df_new


KeyError: ('Sepal.Length', 'Sepal.Width')

In [127]:
df_new.sort_values(by = ['Petal.Length', 'Petal.Width']).reset_index(drop=True)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
0             4.6          3.6           1.0          0.2     setosa
1             4.3          3.0           1.1          0.1     setosa
2             5.8          4.0           1.2          0.2     setosa
3             5.0          3.2           1.2          0.2     setosa
4             4.7          3.2           1.3          0.2     setosa
..            ...          ...           ...          ...        ...
121           7.3          2.9           6.3          1.8  virginica
122           7.9          3.8           6.4          2.0  virginica
123           7.6          3.0           6.6          2.1  virginica
124           7.7          3.8           6.7          2.2  virginica
125           7.7          2.6           6.9          2.3  virginica

[126 rows x 5 columns]